### ISSUE TITLE
Simple shell test suite doesnt check for valgrind errors

### ISSUE THREAD

**Issue by DestinedCodes** [Fuzzworth/alx_test_suite#24]
I used this test suite when i did this project and it helped me a lot but there was a little issue with vlagrind which i overlooked and thought the checker wont care, and it gave me a hard time when the checker was released. i would like this issue to be assigned to me so that i can make the test suite check for valgrind errors and leaks

**Comment by elfadili-ae** [comment]
If we implement everything, the purpose of the project will be defeated.
